[auth]
token = "youmadbro"

[db-config]
database-url = "postgres://bot:bot@localhost:5432/bot"

[bot-config]
command-prefix = "!"
win-sentences = [
    "Bravo {}, plus un dans votre pot Ã  moutarde. A vous la main.",
    "GG {}, un point pour Gryffondor !",
]
ratelimit = { delay = 5, time-span = 30, limit = 4 }

[bot-config.auto-skip]
autoskip-delay = 600
warn-delay = 300

[tracing-config]
otel = "http://localhost:4318/v1/traces"
